### ISSUE TITLE
PF support

### ISSUE THREAD

**Issue by olgeni** [iocage/iocage#875]
Not really an issue but a kind request :)

Would it be possible to add an option to enable pf(4), like it already exists for bpf? It should just make `/dev/pf` show up.

pf(4) seems to work fine inside jails, and it would be useful to have it available without going through rulesets (I tried and failed miserably...)

**Comment by bikingcoder** [comment]
I recently had to go through the pain of making `/dev/pf` appear in an iocage jail. For what it's worth this is the Ansible I ended up cobbling together to create a jail with `/dev/pf` exposed:

```
    - name: add devfs ruleset for exposing pf
      blockinfile:
        path: /etc/defaults/devfs.rules
        marker: "# {mark} pf exposed ruleset"
        block: |
          [devfsrules_pfjail=10000]
          add include $devfsrules_jail
          add path pf unhide

    - name: check ruleset is live
      ansible.builtin.command: devfs rule showsets
      register: rulesets

    - name: make live ruleset change (before reboot)
      ansible.builtin.shell:  |
        devfs rule -s 10000 add include 4
        devfs rule -s 10000 add path pf unhide
      when: "'10000' not in rulesets.stdout"

    - name: Create test jail
      iocage:
        state: present
        name: "{{ jail_name }}"
        release: 12.2-RELEASE
        properties:
          devfs_ruleset: 10000
          ip4_addr: "vnet0|{{jail_ip}}/24"
          vnet: "on"
          boot: "on"
```
It could be cleaner but it works in the simple case where you don't need to edit the rules after the jail has been created. Maybe there's a way to reload the rules without a reboot, but it wasn't obvious at the time?

Hopefully the above helps someone!
